### ISSUE TITLE
[Suggestion] Add a screenshot to README.md

### ISSUE THREAD

**Issue by elimisteve** [panicz/grasp#1]
Then at a glance we can get a sense of what grasp makes possible! Thanks.

**Comment by panicz** [comment]
Thanks for the suggestions (and apologize for the delay in the response, but my activities on github need to align with the space invaders that I draw on my work log).

I think that's a very good idea - but I will wait implementing it until GRASP actually becomes useful (which I think will take a couple more months). Until then I will leave this issue open, and just paste a link to my youtube channel for all those who are impatiently curious:

https://youtube.com/@paniczgodek

**Comment by panicz** [comment]
Oh good, it turns out that github doesn't count writing comments as contributons!

**Comment by panicz** [comment]
I included screenshots from 3 different versions of GRASP, and a link to a demo on youtube. Thanks again for your suggestion!
