### ISSUE TITLE
Could not build desktop client on MacOS

### ISSUE THREAD

**Issue by crmsnbleyd** [panicz/grasp#14]
`++ java -jar ../libs/kawa.jar --no-warn-unreachable -f analdep.scm -- --list grasp-desktop.scm
java.io.FileNotFoundException: /check-comments.scm (No such file or directory)`
	
	
And later we get the error 

`Archive:  kawa.jar
  inflating: META-INF/MANIFEST.MF
Illegal option: -
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...`

After these errors, the jar cannot be found in the build directory

**Comment by panicz** [comment]
It looks like I need to get myself a mac.

Could you try replacing the definition of `module-name` in `src/analdep.scm` with the following one:

    (define (module-name file)
      (map string->symbol
           (only (is (length _) > 0)
                 (string-split (string-take file
                                            (- (length file) 4))
                               "/"))))

and let me know if that helps?

**Comment by pfusik** [comment]
> Could you try replacing the definition of module-name in src/analdep.scm with the following one:

Doesn't help.
