### ISSUE TITLE
VImism of grasp-terminal

### ISSUE THREAD

**Issue by pfusik** [panicz/grasp#18]
How do I exit it?

**Comment by panicz** [comment]
Why would you? ;]

Currently it's either F12, or you could evaluate (ctrl+e) the (exit) expression.

**Comment by panicz** [comment]
Also, the following methods are universal: 
https://www.quora.com/profile/Panicz-Godek/10-Effective-Ways-to-Exit-Vim

**Comment by pfusik** [comment]
Thanks!
